WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
INFO:__main__:Bot and token initialized
INFO:discord.client:logging in using static token
INFO:discord.gateway:Shard ID None has connected to Gateway (Session ID: e6f26680727d5fd4a8e8a7c1eccdcbb3).
ERROR:discord.client:Ignoring exception in on_message
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/ext/commands/bot.py", line 1227, in get_prefix
    ret = list(ret)  # type: ignore
          ^^^^^^^^^
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/client.py", line 504, in _run_event
    await coro(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/ext/commands/bot.py", line 1421, in on_message
    await self.process_commands(message)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/ext/commands/bot.py", line 1416, in process_commands
    ctx = await self.get_context(message)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/ext/commands/bot.py", line 1315, in get_context
    prefix = await self.get_prefix(origin)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/ext/commands/bot.py", line 1234, in get_prefix
    raise TypeError(
TypeError: command_prefix must be plain string, iterable of strings, or callable returning either of these, not NoneType
ERROR:discord.client:Ignoring exception in on_message
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/ext/commands/bot.py", line 1227, in get_prefix
    ret = list(ret)  # type: ignore
          ^^^^^^^^^
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/client.py", line 504, in _run_event
    await coro(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/ext/commands/bot.py", line 1421, in on_message
    await self.process_commands(message)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/ext/commands/bot.py", line 1416, in process_commands
    ctx = await self.get_context(message)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/ext/commands/bot.py", line 1315, in get_context
    prefix = await self.get_prefix(origin)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/ext/commands/bot.py", line 1234, in get_prefix
    raise TypeError(
TypeError: command_prefix must be plain string, iterable of strings, or callable returning either of these, not NoneType
ERROR:discord.client:Ignoring exception in on_message
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/ext/commands/bot.py", line 1227, in get_prefix
    ret = list(ret)  # type: ignore
          ^^^^^^^^^
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/client.py", line 504, in _run_event
    await coro(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/ext/commands/bot.py", line 1421, in on_message
    await self.process_commands(message)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/ext/commands/bot.py", line 1416, in process_commands
    ctx = await self.get_context(message)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/ext/commands/bot.py", line 1315, in get_context
    prefix = await self.get_prefix(origin)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/ext/commands/bot.py", line 1234, in get_prefix
    raise TypeError(
TypeError: command_prefix must be plain string, iterable of strings, or callable returning either of these, not NoneType
ERROR:discord.client:Ignoring exception in on_message
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/ext/commands/bot.py", line 1227, in get_prefix
    ret = list(ret)  # type: ignore
          ^^^^^^^^^
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/client.py", line 504, in _run_event
    await coro(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/ext/commands/bot.py", line 1421, in on_message
    await self.process_commands(message)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/ext/commands/bot.py", line 1416, in process_commands
    ctx = await self.get_context(message)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/ext/commands/bot.py", line 1315, in get_context
    prefix = await self.get_prefix(origin)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/ext/commands/bot.py", line 1234, in get_prefix
    raise TypeError(
TypeError: command_prefix must be plain string, iterable of strings, or callable returning either of these, not NoneType
ERROR:discord.client:Ignoring exception in on_message
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/ext/commands/bot.py", line 1227, in get_prefix
    ret = list(ret)  # type: ignore
          ^^^^^^^^^
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/client.py", line 504, in _run_event
    await coro(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/ext/commands/bot.py", line 1421, in on_message
    await self.process_commands(message)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/ext/commands/bot.py", line 1416, in process_commands
    ctx = await self.get_context(message)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/ext/commands/bot.py", line 1315, in get_context
    prefix = await self.get_prefix(origin)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/ext/commands/bot.py", line 1234, in get_prefix
    raise TypeError(
TypeError: command_prefix must be plain string, iterable of strings, or callable returning either of these, not NoneType
ERROR:discord.client:Ignoring exception in on_message
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/ext/commands/bot.py", line 1227, in get_prefix
    ret = list(ret)  # type: ignore
          ^^^^^^^^^
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/client.py", line 504, in _run_event
    await coro(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/ext/commands/bot.py", line 1421, in on_message
    await self.process_commands(message)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/ext/commands/bot.py", line 1416, in process_commands
    ctx = await self.get_context(message)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/ext/commands/bot.py", line 1315, in get_context
    prefix = await self.get_prefix(origin)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/discord/ext/commands/bot.py", line 1234, in get_prefix
    raise TypeError(
TypeError: command_prefix must be plain string, iterable of strings, or callable returning either of these, not NoneType
